# This file was mostly generated by vtcl-1.5.2
# I did the layout there, then hacked it up mostly
# because I'm not sure how to get vtcl to do what
# I want so it's easier to fix it by hand.  In the process
# I removed the font 'support' stuff that was added automatically
# (things like get_font etc) because I've got my own font
# mechanism - there's a global set of font names for the
# environment that are set in the fonts.tcl init file.



global copyrightlab30var 
   
proc select_copyrights {} {
  global got_actr_connection
  global environment_socket
  global options_array
  global screen_center_x
  global screen_center_y

  if {[winfo exists .copyright] == 1} {
    wm deiconify .copyright
    focus -force .copyright
  } else {
    # here the window gets created and set up

    toplevel .copyright
    wm withdraw .copyright

    wm geometry .copyright \
    "400x290+[expr $screen_center_x - 200]+[expr $screen_center_y - 145]"

    global tcl_platform

    if {$tcl_platform(os) != "Darwin"} {
      wm overrideredirect .copyright 1
    }

    label .copyright.lab22 -font intro_l_font -height 1 -text {ACT-R Environment} -anchor center
    label .copyright.lab30 -font intro_l_font -height 2 -textvariable copyrightlab30var -anchor center
    label .copyright.lab24 -font intro_s_font -height 1 -text "\u00a9 2002-2019" -anchor center
    label .copyright.lab33 -font intro_s_font -height 1 -anchor center -text {Dan Bothell} 
    label .copyright.lab43 -font intro_s_font -height 1 -anchor center -text {John R. Anderson}  
    label .copyright.lab35 -font intro_s_font -height 1 -anchor center -text {Department of Psychology, Carnegie Mellon University}  

    global tcl_env_dir

    image create photo small_onr_logo -file [file join $tcl_env_dir dialogs smalllogo.gif]

    label .copyright.image -width 400 -height 142 -anchor center -image small_onr_logo


    ###################
    # SETTING GEOMETRY
    ###################
    pack .copyright.lab22
    pack .copyright.lab30 
    pack .copyright.lab24
    pack .copyright.lab33
    pack .copyright.lab43
    pack .copyright.lab35
    pack .copyright.image

    # get the version strings, but being careful because an
    # overzelous clicker could clear the dialog before the 
    # register messages arrive, so make sure the update messages
    # arrive (they're sent after the registers) before showing
    # the window

    global copyrightlab30var 

    set copyrightlab30var [call_act_r_command "act-r-version"]

    # show the window if the user wants it
    # sort of cheats because it still gets "built"

    if {$options_array(show_copyrights) == 1} {
      wm deiconify .copyright
    }
  }
}



select_copyrights

# then if it's supposed to be shown 

if {$options_array(show_copyrights) == 1} {

  # create a variable that will trigger the destruction of the window
  # after 5 seconds or when the window is clicked

  set clear_copyright 0

  # set the variable that triggers destruction after 3 seconds
  # or as soon as a button is pressed on the window

  after 5000 {set clear_copyright 1}
  bind .copyright <ButtonPress> {set clear_copyright 1}

  # wait for one of the triggering events to happen

  tkwait variable clear_copyright
}

# close the window

destroy .copyright

