name: Release ACT-R Slim
on:
  release:
    types: [created]

jobs:
  slim:
    name: Release ACT-R Slim
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Slim Archive
        # "slim" removes examples, tutorials, and extras
        run: zip -r actr-slim-${{ github.event.release.tag_name }}.zip . -x \*.git\* \*.DS_Store \*.zip examples/\* extras/\* other-files/\* tutorial/\*
      - name: Slim (no env) Archive
        # "super slim" also removes the docs and (most of) the environment
        run: zip -r actr-super-slim-${{ github.event.release.tag_name }}.zip . -x \*.git\* \*.DS_Store \*.zip docs/\* environment/\*.exe environment/GUI/\* environment/alternate-\* environment/run-\* environment/start\* examples/\* extras/\* other-files/\* tutorial/\*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            actr-slim-${{ github.event.release.tag_name }}.zip
            actr-super-slim-${{ github.event.release.tag_name }}.zip
